### PR TITLE
Fix for the last checkin

### PR DESCRIPTION
**Pull request by emipa606**
Not sure if you are planning on continue the mod but I repaired the latest checkin if you want to have a working last version.

- Project moved to .NET Sdk instead of the old .Net framework
- All classes moved to separate files
- Some code refactoring
- Put the split workGiver for quality frames inside a #if DEBUG as it wasnt finished
- Added the missing translation-strings for English

Hope it helps!

### CODE REVIEW

**Comment by oorzkws** [comment]
Thanks for posting your changes, I appreciate being to use the updated copy

Edit: With this build when dragging categories, they always end up dropping one slot above or below where they're actually dropped.

**Comment by densevoid** [comment]
Do these changes bring some kind of benefit for the players? Any bugs are fixed here, for example?

**Comment by emipa606** [comment]
No idea, I just fixed the errors in the last commit.

**Comment by densevoid** [comment]
It's funny that you removed the additional VS files in your first commit. And then generated them yourself in another place and committed again :)

Well, I completed merge. But I think there is no special sense to fill this version into the game now.

**Comment by emipa606** [comment]
Yea, git has its own ideas sometimes 😄

**Pull request merged**
